### ISSUE TITLE
Once again flagged as a Virus

### ISSUE THREAD

**Issue by JustAnotherU5er** [NotNite/GDWeave#34] opened 2024-12-05 02:57 UTC
Seems to be detected as `PUA:Win32/Vigua.A` and `PUA:Win32/Packunwan` now not sure what's up with that.

![image](https://github.com/user-attachments/assets/8566beae-04d5-42bf-b69f-8a2469abeaec)

![image](https://github.com/user-attachments/assets/02d234cd-888f-4de5-a030-fd8aad5eb83a)

I'm sure its a false positive but the multiple times its getting flagged does feel suspicious.
Other people having the same issue but detected as a different virus still looks odd.

**Comment by NotNite** [comment] 2024-12-05 02:59
Duplicate of #25, closing.

> I'm sure its a false positive but the multiple times its getting flagged does feel suspicious.

I did not change anything. You can verify this with hash checking as described in other issues.

**Closed by NotNite** 2024-12-05 02:59 UTC

**Comment by JustAnotherU5er** [comment] 2024-12-05 03:20
Never stated you did change anything just noticed its being flagged as something else now compared to what other people say its being flagged as. Windows defender a little confused but got the spirit

**Comment by RecoveryDeer** [comment] 2024-12-06 23:41
Hi hi, this is happening for me as well. Is it safe to flag for ignoring?
